DROP TABLE IF EXISTS items;

CREATE TABLE items(
    item_id INT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    price INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);